import { createRequire } from "node:module";
import assert from "node:assert/strict";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || "C:/Users/harsh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright");
const browser = await chromium.launch({channel:"chrome", headless:true});
const page = await browser.newPage({viewport:{width:1366,height:1000}});
const errors=[];
page.on("pageerror", error=>errors.push(error.message));
await page.route("**/api/**", async route=>{
  const req=route.request();
  const url=new URL(req.url());
  const response=await route.fetch({url:"http://127.0.0.1:8001"+url.pathname+url.search});
  await route.fulfill({response});
});
await page.addInitScript(()=>sessionStorage.setItem("mausam-mvp-ready","yes"));
try {
  await page.goto("http://127.0.0.1:5173/");
  await page.getByRole("button",{name:"Report local weather",exact:true}).waitFor({timeout:60000});
  await page.getByRole("button",{name:"Report local weather",exact:true}).click();
  await page.getByLabel("Area or landmark").fill("QA underpass — isolated test");
  await page.getByLabel("Details (optional)").fill("One lane has standing water.");
  await page.getByRole("button",{name:"Submit community report",exact:true}).click();
  await page.getByText("Report saved.",{exact:false}).waitFor();
  await page.reload();
  await page.getByText("QA underpass — isolated test · Ahmedabad",{exact:true}).waitFor({timeout:60000});
  await page.locator(".sidebar").getByRole("button",{name:/Alerts/}).click();
  await page.getByText("QA underpass — isolated test · Ahmedabad",{exact:true}).waitFor();
  const explanations=page.getByRole("button",{name:/Why am I seeing this/});
  if(await explanations.count())await explanations.first().click();
  await page.locator(".sidebar").getByRole("button",{name:"Profile",exact:true}).click();
  await page.getByPlaceholder("Add another preference").fill("Swimming");
  await page.getByRole("button",{name:"Add preference",exact:true}).click();
  await page.getByLabel("Typical departure time").fill("08:15");
  await page.getByLabel("Daily needs").fill("School pickup");
  await page.getByRole("button",{name:/Priority notifications/}).click();
  await page.getByRole("button",{name:"Save preferences",exact:true}).click();
  await page.getByText("Preferences saved.",{exact:false}).waitFor();
  await page.getByRole("button",{name:"Notifications",exact:true}).click();
  await page.getByText("Notifications are paused in Profile.",{exact:true}).waitFor();
  await page.getByRole("button",{name:"Close notifications"}).click();
  await page.reload();
  await page.locator(".sidebar").getByRole("button",{name:"Profile",exact:true}).click({timeout:60000});
  await page.getByLabel("Typical departure time").waitFor();
  assert.equal(await page.getByLabel("Typical departure time").inputValue(),"08:15");
  assert.equal(await page.getByLabel("Daily needs").inputValue(),"School pickup");
  assert.equal(await page.getByRole("button",{name:"Swimming",exact:true}).getAttribute("aria-pressed"),"true");
  await page.locator(".sidebar").getByRole("button",{name:"Home",exact:true}).click();
  await page.locator(".city-select select").selectOption("Mumbai");
  await page.getByRole("button",{name:"Report local weather",exact:true}).waitFor({timeout:60000});
  assert.equal(await page.getByText("QA underpass — isolated test · Ahmedabad",{exact:true}).count(),0);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true,"Mobile page must not overflow");
  await page.getByRole("button",{name:"Report local weather",exact:true}).click();
  await page.getByLabel("Area or landmark").waitFor();
  await page.screenshot({path:"docs/qa/mobile-local-report.png",fullPage:true});
  assert.deepEqual(errors,[]);
  console.log("PASS: Home report submission; refresh persistence; Alerts visibility; preference persistence; paused notifications; location filtering; mobile layout; no runtime errors.");
} finally { await browser.close(); }
