import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Activity, AlertTriangle, ArrowRight, Bell, Bike, Check, ChevronDown, ChevronRight, CloudRain, CloudSun, Compass, Droplets, Home, Info, Leaf, LoaderCircle, LocateFixed, MapPin, Menu, Navigation, Plus, Save, Search, Settings2, ShieldCheck, Sparkles, Sun, ThermometerSun, User, Users, Wind, X } from "lucide-react";
import { addLocation, getDemo, getFeed, getLocations, getObservations, getProfile, markNotificationRead, reportObservation, searchLocations, updatePreferences } from "./services/api";
import type { Feed, LocationSearchResult, Observation, Persona, Recommendation, SavedLocation, UserProfile, WeatherAlert } from "./types";
import { personaDetails } from "./types";

type View = "home" | "forecast" | "alerts" | "locations" | "profile" | "demo";
const personas = Object.keys(personaDetails) as Persona[];
const corePersonas: Persona[] = ["fitness","family","agriculture","travel"];
const onboardingPersonas: Persona[] = ["fitness","family","agriculture","travel","commuter","outdoor_worker","general"];
const cities = ["Ahmedabad", "Mumbai", "Delhi"];
const personaMeta: Record<Persona, {title:string; label:string; icon:typeof Bike; focus:string; cta:string}> = {
  fitness:{title:"Fitness & Cycling",label:"Fitness",icon:Bike,focus:"Wind drag · Peak UV window",cta:"View activity suitability"},
  family:{title:"Family & Kids",label:"Family",icon:Users,focus:"Heat exposure · School commute",cta:"View family outdoor plan"},
  agriculture:{title:"Farmer / Agronomy",label:"Farmer",icon:Leaf,focus:"Rain window · Wind · Irrigation",cta:"View farm weather"},
  travel:{title:"Traveler / Transit",label:"Traveler",icon:Navigation,focus:"Destination rain · Packing",cta:"View trip plan"},
  health:{title:"Health & Comfort",label:"Health",icon:Activity,focus:"AQI · Heat · UV · Humidity",cta:"View environmental conditions"},
  commuter:{title:"Daily Commuter",label:"Commuter",icon:Navigation,focus:"Routine time · Rain · Visibility",cta:"View commute conditions"},
  outdoor_worker:{title:"Outdoor Worker",label:"Outdoor worker",icon:User,focus:"Heat exposure · Break window",cta:"View work-risk guidance"},
  event:{title:"Event Planner",label:"Events",icon:Users,focus:"Comfort · Rain · Wind",cta:"View event suitability"},
  general:{title:"Everyday Weather",label:"General",icon:CloudSun,focus:"Top preventive action",cta:"View today’s guidance"},
};

function Logo(){return <div className="logo-wrap"><span className="logo-mark"><CloudSun size={20}/></span><div><strong>Mausam<span>+</span></strong><small>One weather. Different intelligence.</small></div></div>}

function AppShell({view,setView,children,feed,location,setLocation,onRefresh}:{view:View;setView:(v:View)=>void;children:React.ReactNode;feed:Feed;location:string;setLocation:(v:string)=>void;onRefresh:()=>void}){
 const [mobileOpen,setMobileOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false),[query,setQuery]=useState(""),[results,setResults]=useState<LocationSearchResult[]>([]),[searching,setSearching]=useState(false);
 const nav=[{id:"home" as View,label:"Home",icon:Home},{id:"forecast" as View,label:"Forecast",icon:CloudSun},{id:"alerts" as View,label:"Alerts",icon:AlertTriangle},{id:"locations" as View,label:"Locations",icon:MapPin},{id:"profile" as View,label:"Profile",icon:User}];
 const go=(id:View)=>{setView(id);setMobileOpen(false);setSearchOpen(false);setNotificationsOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
 useEffect(()=>{if(!searchOpen||query.trim().length<2){setResults([]);return}const timer=window.setTimeout(()=>{setSearching(true);searchLocations(query).then(setResults).catch(()=>setResults([])).finally(()=>setSearching(false))},300);return()=>window.clearTimeout(timer)},[query,searchOpen]);
 const choose=(name:string)=>{setLocation(name);setSearchOpen(false);setQuery("");go("home")};
 const selectorCities=[location,...cities.filter(city=>city!==location)];
 return <div className="app-shell"><aside className={`sidebar ${mobileOpen?"open":""}`}><div><Logo/><nav aria-label="Primary navigation">{nav.map(item=>{const Icon=item.icon;return <button key={item.id} className={view===item.id?"active":""} onClick={()=>go(item.id)}><Icon size={19}/><span>{item.label}</span>{item.id==="alerts"&&feed.alerts.length>0&&<em>{feed.alerts.length} warning</em>}</button>})}</nav></div><div className="sandbox-card"><span>Personalization lab</span><Settings2 size={15}/><p>Compare how one weather snapshot changes for every persona.</p><button onClick={()=>go("demo")}><Compass size={15}/> Demo mode</button></div><button className="close-menu" onClick={()=>setMobileOpen(false)} aria-label="Close navigation"><X/></button></aside>
 <div className="app-main"><header className="topbar"><button className="menu-button" onClick={()=>setMobileOpen(true)} aria-label="Open navigation"><Menu/></button><div className="mobile-logo"><Logo/></div><label className="city-select"><MapPin size={15}/><select value={location} onChange={e=>setLocation(e.target.value)}>{selectorCities.map(c=><option key={c} value={c}>{c}</option>)}</select><ChevronDown size={14}/></label><span className={`data-chip ${feed.is_demo_data?"fallback":"live"}`}>{feed.is_demo_data?"Fallback data":"Live data"}</span><div className="top-spacer"/><span className="condition-chip"><Sun size={15}/>{feed.weather.condition} · {feed.weather.temperature}°C</span><button className="icon-button" aria-label="Search locations" aria-expanded={searchOpen} onClick={()=>{setSearchOpen(!searchOpen);setNotificationsOpen(false)}}><Search size={18}/></button><button className={`icon-button ${feed.notifications.length?"bell":""}`} aria-label="Notifications" aria-expanded={notificationsOpen} onClick={()=>{setNotificationsOpen(!notificationsOpen);setSearchOpen(false)}}><Bell size={18}/></button><button className="avatar-button" onClick={()=>go("profile")} aria-label="Open profile"><span className="avatar">A</span><span className="user-name">Aarav<small>Mausam+ user</small></span></button></header>
 {searchOpen&&<div className="top-popover search-popover"><div className="popover-title"><b>Search weather anywhere</b><button onClick={()=>setSearchOpen(false)} aria-label="Close search"><X/></button></div><label><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="City or district"/></label>{searching&&<p><LoaderCircle className="spin"/> Searching…</p>}{!searching&&query.length>=2&&results.length===0&&<p>No matching locations yet.</p>}{results.map(result=><button className="search-result" key={`${result.latitude}-${result.longitude}`} onClick={()=>choose(result.name)}><MapPin/><span><b>{result.name}</b><small>{[result.admin1,result.country].filter(Boolean).join(", ")}</small></span><ArrowRight/></button>)}</div>}
 {notificationsOpen&&<div className="top-popover notification-popover"><div className="popover-title"><b>Notifications</b><button onClick={()=>setNotificationsOpen(false)} aria-label="Close notifications"><X/></button></div>{feed.notifications.map(alert=><div className="notification-item" key={alert.id}><button className="ghost-link" onClick={()=>go("alerts")}><AlertTriangle/><span><b>{alert.title}</b><small>{alert.severity} · {alert.valid_at}</small></span></button><button className="ghost-link" aria-label={`Mark ${alert.title} read`} onClick={()=>markNotificationRead(alert.id).then(onRefresh).catch(()=>window.alert("Could not mark read. Please retry."))}><Check/></button></div>)}{!feed.notifications.length&&<p className="empty-state">{feed.notifications_enabled?"You’re up to date. No unread priority alerts.":"Notifications are paused in Profile."}</p>}<button className="popover-footer" onClick={()=>go("alerts")}>View all alerts</button></div>}
 {children}<nav className="bottom-nav">{nav.map(item=>{const Icon=item.icon;return <button key={item.id} className={view===item.id?"active":""} onClick={()=>go(item.id)}><Icon size={20}/><span>{item.label}</span></button>})}</nav></div></div>
}

function PageHeading({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy?:string;action?:React.ReactNode}){return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{copy&&<p>{copy}</p>}</div>{action}</div>}

function PersonaPicker({persona,setPersona}:{persona:Persona;setPersona:(p:Persona)=>void}){const [open,setOpen]=useState(false);const meta=personaMeta[persona];const Icon=meta.icon;return <div className="persona-picker"><button onClick={()=>setOpen(!open)}><Icon size={17}/>{meta.label} mode<ChevronDown size={15}/></button>{open&&<div className="persona-menu">{personas.map(p=>{const m=personaMeta[p],I=m.icon;return <button key={p} className={persona===p?"active":""} onClick={()=>{setPersona(p);setOpen(false)}}><I size={17}/><span><b>{m.label}</b><small>{m.focus}</small></span>{persona===p&&<Check size={16}/>}</button>})}</div>}</div>}

function WeatherHero({feed}:{feed:Feed}){const w=feed.weather;return <section className="weather-hero"><div className="weather-line line-one"/><div className="weather-line line-two"/><div className="hero-location"><Navigation size={15}/><span>{w.location.toUpperCase()}</span></div><div className="hero-core"><div><p>{w.condition}</p><span className="update">{w.updated_at}</span></div><div className="big-weather"><CloudSun/><strong>{w.temperature}°</strong><span>C<small>Feels like {w.feels_like}°</small></span></div></div><div className="metric-grid"><div><ThermometerSun/><span>Feels like</span><strong>{w.feels_like}°C</strong><small>Current apparent temperature</small></div><div><Droplets/><span>Humidity</span><strong>{w.humidity}%</strong><small>Current relative humidity</small></div><div><Wind/><span>Wind</span><strong>{w.wind_speed} km/h</strong><small>Current wind speed</small></div><div><Sun/><span>UV index</span><strong>{w.uv_index}</strong><small>Forecast UV index</small></div></div><div className="source-line"><span>Source: {feed.provider} · AQI: CAMS via Open-Meteo</span><span>{feed.is_demo_data?"Illustrative sample weather":"Auto-refreshes every 5 minutes"}</span></div></section>}

function InsightCard({item,persona,onAction}:{item:Recommendation;persona:Persona;onAction:()=>void}){const [why,setWhy]=useState(false),meta=personaMeta[persona];return <section className="insight-card"><div className="insight-top"><span className="persona-tag">Personalized insight · {meta.label}</span><strong><Activity size={17}/> Score {item.score}/100</strong></div><div className="insight-copy"><h2>{personaDetails[persona].icon} {item.title}</h2><p>{item.message} {item.action}.</p></div><div className="insight-actions"><button className="ghost-link" onClick={()=>setWhy(!why)}><Info size={17}/>{why?"Hide explanation":"Why am I seeing this?"}</button><button className="secondary-cta" onClick={onAction}>{meta.cta}<ArrowRight size={16}/></button></div>{why&&<div className="why-panel"><span><Sparkles size={15}/> Rules that shaped this insight</span><div>{item.reason.map(r=><p key={r}><Check size={15}/>{r}</p>)}</div></div>}</section>}

function AlertStrip({feed,goAlerts}:{feed:Feed;goAlerts:()=>void}){const a=feed.alerts[0];return <section className="alert-strip"><span className="alert-symbol">{a?<AlertTriangle/>:<ShieldCheck/>}</span><div><span className={`severity ${a?.severity.toLowerCase()??"low"}`}>{a?.severity??"No elevated alerts"} · {a?.source??"Available forecast"}</span><h3>{a?.title??"No alert threshold reached"}</h3><p>{a?.message??"Check official updates before weather-sensitive plans."}</p></div><button onClick={goAlerts}>View alerts and local reports <ArrowRight size={15}/></button></section>}

function Timeline({feed}:{feed:Feed}){return <section className="section-block"><div className="section-heading"><div><h2>Next 24 hours</h2><span>{Math.ceil(feed.hourly.length/4)} intervals</span></div><small>Live forecast shaped for your current mode</small></div><div className="timeline-grid">{feed.hourly.filter((_,i)=>i%4===0).map((h,i)=><article key={h.time} className={i===0?"active":""}><div><span>{h.time}</span><b>{h.icon}</b></div><h3>{h.event}</h3><strong>{h.temp}°C</strong><small>{i===0?"Current window":"Forecast interval"}</small></article>)}</div></section>}

function Weekly({feed,compact=false,onOpen}:{feed:Feed;compact?:boolean;onOpen?:()=>void}){return <section className="panel-card weekly"><div className="card-heading"><div><span className="eyebrow">Extended horizon</span><h2>{compact?"This week":"7-day trajectory outlook"}</h2></div><CloudSun/></div>{feed.daily.map((d)=><div className="forecast-row" key={d.day}><strong>{d.day}</strong><span className="day-icon">{d.icon}</span><span>{d.condition??"Demo forecast"}</span><em>{d.rain}%</em><b>{d.high}° <small>/ {d.low}°</small></b></div>)}{onOpen&&<button className="ghost-link" onClick={onOpen}>View 7-day forecast <ArrowRight size={15}/></button>}</section>}

function ImpactCard({feed}:{feed:Feed}){const [open,setOpen]=useState(false);return <section className="panel-card impact-card"><div><span className="eyebrow">Explainable personal score</span><h2>Your weather impact</h2></div><div className="impact-content"><span className="score-ring" style={{"--score":`${feed.impact.score*3.6}deg`} as React.CSSProperties}><b>{feed.impact.score}</b></span><div><strong>{feed.impact.level} relevance today</strong><p>Ranked from your persona and today’s weather.</p></div></div><button className="ghost-link" onClick={()=>setOpen(!open)}>{open?"Hide contribution":"See score contribution"}<ChevronDown size={14}/></button>{open&&<div className="factor-breakdown">{feed.impact.factors.map(f=><p key={f.name}><span>{f.name}<small>{f.explanation}</small></span><b>+{f.contribution}</b></p>)}</div>}<small className="score-note">Mausam+ personalization indicator, not an official risk index.</small></section>}

function SavedPreview({onOpen}:{onOpen:()=>void}){const [places,setPlaces]=useState<SavedLocation[]>([]);useEffect(()=>{getLocations().then(setPlaces).catch(()=>undefined)},[]);return <section className="panel-card saved-preview"><div className="card-heading"><div><span className="eyebrow">Pinned places</span><h2>Saved locations</h2></div><button onClick={onOpen} aria-label="Manage saved places">+</button></div><div>{places.map(place=><article key={place.id}><b>{place.name}</b><span>{place.label}</span></article>)}</div><button className="ghost-link" onClick={onOpen}>Manage locations <ArrowRight size={15}/></button></section>}

function HomePage({feed,persona,setPersona,setView}:{feed:Feed;persona:Persona;setPersona:(p:Persona)=>void;setView:(v:View)=>void}){return <main className="page"><PageHeading eyebrow="Daily briefing · Updated automatically" title="Good morning, Aarav" action={<PersonaPicker persona={persona} setPersona={setPersona}/>}/><WeatherHero feed={feed}/><InsightCard item={feed.recommendations[0]} persona={persona} onAction={()=>setView("forecast")}/><section className="next-actions"><div><span className="eyebrow">Next best actions</span><h2>After your top recommendation</h2></div>{feed.recommendations.slice(1,3).map(r=><article key={r.id}><span>{r.badge}</span><h3>{r.title}</h3><p>{r.message}</p><b>{r.action}</b></article>)}</section><AlertStrip feed={feed} goAlerts={()=>setView("alerts")}/><Timeline feed={feed}/><section className="home-lower"><Weekly feed={feed} compact onOpen={()=>setView("forecast")}/><div className="stacked-cards"><ImpactCard feed={feed}/><SavedPreview onOpen={()=>setView("locations")}/></div></section><CommunityPanel feed={feed}/></main>}

function ForecastPage({feed,persona}:{feed:Feed;persona:Persona}){
 const [selectedDay,setSelectedDay]=useState(0);const day=feed.daily[selectedDay]??feed.daily[0];const hours=feed.hourly.filter(hour=>day?.date?hour.timestamp?.startsWith(day.date):true);const meta=personaMeta[persona];const window=feed.recommendations.find(item=>item.id==="activity-window");
 return <main className="page"><PageHeading eyebrow={feed.is_demo_data?"Demo forecast":"Weather forecast"} title={`Plan for ${feed.weather.location}`} copy={`Guidance for ${meta.title.toLowerCase()}.`}/><div className="day-tabs">{feed.daily.map((d,i)=><button key={d.day} className={selectedDay===i?"active":""} aria-pressed={selectedDay===i} onClick={()=>setSelectedDay(i)}><small>{d.day}</small><strong>{d.rain}% rain</strong><span>{d.icon}</span></button>)}</div>{day&&<section className="forecast-feature"><span className="persona-tag">{day.day} · {day.date}</span><div className="forecast-big"><strong>{day.high}°</strong><span>/ {day.low}°C</span><h2>{day.condition??"Demonstration forecast"}</h2></div></section>}<section className="section-block"><h2>Your plan</h2>{window&&<p>{window.message} {window.action}.</p>}<div className="next-actions">{feed.recommendations.map(item=><article key={item.id}><span>{item.badge} · relevance {item.score}/100</span><h3>{item.title}</h3><p>{item.message}</p><b>{item.action}</b><details><summary>Why am I seeing this?</summary>{item.reason.map(reason=><p key={reason}>{reason}</p>)}</details></article>)}</div></section><h2 className="subhead">Forecast intervals for {day?.day}</h2><div className="dayparts">{hours.map(h=><article key={h.timestamp??h.time}><span>{h.time}</span><h3>{h.temp}°C · {h.event}</h3><p>Rain {h.rain??"—"}% · Wind {h.wind??"—"} km/h · UV {h.uv??"—"}</p></article>)}</div>{!hours.length&&<p className="empty-state">Hourly planning is available for the next 24 hours. Use the daily outlook for later dates.</p>}<Weekly feed={feed}/></main>
}

function AlertCard({alert,open=false}:{alert:WeatherAlert;open?:boolean}){
 const [expanded,setExpanded]=useState(open);
 return <article className="alert-card"><div className="alert-card-top"><span className={`severity ${alert.severity.toLowerCase()}`}>{alert.severity} · {alert.source}</span><span>{alert.valid_at} · {alert.location}</span></div><div className="alert-title"><span><AlertTriangle/></span><div><h2>{alert.title}</h2><p>{alert.message}</p></div></div><p>Personal relevance: {alert.rank}/100</p><button className="why-toggle" onClick={()=>setExpanded(value=>!value)} aria-expanded={expanded}><Info size={17}/> Why am I seeing this? <ChevronDown size={16}/></button>{expanded&&<div className="alert-reason">{alert.reason.map(reason=><p key={reason}>{reason}</p>)}{alert.actions.map(action=><strong key={action}>{action}</strong>)}</div>}</article>
}

function CommunityPanel({feed,onChanged}:{feed:Feed;onChanged?:()=>void}){
 const [open,setOpen]=useState(false),[kind,setKind]=useState("waterlogging"),[area,setArea]=useState(""),[details,setDetails]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[reports,setReports]=useState<Observation[]>(feed.observations);
 useEffect(()=>{let active=true;setReports(feed.observations);const load=()=>getObservations(feed.weather.location).then(rows=>{if(active)setReports(rows)}).catch(()=>{if(active)setMessage("Reports could not be refreshed. Try again shortly.")});load();const timer=window.setInterval(load,60000);return()=>{active=false;clearInterval(timer)}},[feed.weather.location,feed.observations]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setMessage("");try{const report=await reportObservation(kind,feed.weather.location,area.trim(),details.trim());setReports(current=>[report,...current.filter(item=>item.id!==report.id)]);setMessage("Report saved. It is now visible below as an unverified community observation.");setOpen(false);setArea("");setDetails("");onChanged?.()}catch{setMessage("Could not save the report. Your entered details are still here; please retry.")}finally{setBusy(false)}};
 return <section className="community-panel" id="community-reports"><div className="community-heading"><div><span className="eyebrow">Street-level context · {feed.weather.location}</span><h2>Local weather reports</h2><p>Community observations from the last 24 hours. These are not official warnings.</p></div><button className="primary-cta" onClick={()=>setOpen(value=>!value)} aria-expanded={open}>{open?"Close report form":"Report local weather"}</button></div>
 {open&&<form className="report-form" onSubmit={submit}><label>What are you seeing?<select value={kind} onChange={e=>setKind(e.target.value)}>{[["rainfall","Heavy rainfall"],["waterlogging","Waterlogging"],["fallen_tree","Fallen tree"],["flooded_road","Flooded road"],["hail","Hail"],["lightning","Lightning"],["strong_wind","Strong winds"],["fog","Fog"]].map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></label><label>Area or landmark<input required maxLength={120} value={area} onChange={e=>setArea(e.target.value)} placeholder="e.g. SG Highway, near the underpass"/></label><label>Details (optional)<input maxLength={500} value={details} onChange={e=>setDetails(e.target.value)} placeholder="What is happening at this place?"/></label><button type="submit" disabled={busy||!area.trim()}>{busy?"Saving…":"Submit community report"}</button><small>City: {feed.weather.location}. Do not include personal contact details.</small></form>}
 {message&&<p className="form-message" role="status">{message}</p>}<div className="observation-list">{reports.map(o=><article key={o.id}><span>Community reported · unverified</span><b>{o.type.replaceAll("_"," ")}</b><p>{o.area||o.location} · {o.location}</p>{o.details&&<p>{o.details}</p>}<time dateTime={o.reported_at}>{new Date(o.reported_at).toLocaleString()}</time></article>)}</div>{reports.length===0&&<p className="empty-state">No local reports yet. Add an observation to help others understand conditions nearby.</p>}</section>
}

function AlertsPage({feed,persona}:{feed:Feed;persona:Persona}){
 const [filter,setFilter]=useState("All");const alerts=feed.alerts.filter(alert=>filter==="All"||alert.severity===filter);
 return <main className="page"><section className="alerts-hero"><span className="eyebrow">Personalized alert stream</span><h1>Weather alerts</h1><p>Ranked for your {personaMeta[persona].label.toLowerCase()} plans in {feed.weather.location}.</p><div className="alert-filters">{["All","Critical","High","Moderate","Low"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></section><div className="alerts-layout"><div className="alert-list">{alerts.map((alert,i)=><AlertCard key={alert.id} alert={alert} open={i===0}/>)}{!alerts.length&&<p className="empty-state">No {filter==="All"?"elevated":filter.toLowerCase()} alerts from the available data for this location.</p>}</div><aside><ImpactCard feed={feed}/><section className="integrity-card"><ShieldCheck/><h3>Source clarity</h3><p>Forecast: {feed.provider}.</p>{feed.data_gaps.map(gap=><p key={gap}>{gap}</p>)}<a href="https://mausam.imd.gov.in/" target="_blank" rel="noreferrer">View official IMD updates</a></section><section className="panel-card"><h3>Notification priority</h3><p>{feed.notifications_enabled?"Only high-relevance alerts for the next six hours enter your notification inbox. Read alerts stay acknowledged.":"Your notification inbox is paused in Profile. All alerts remain available here."}</p></section></aside></div><CommunityPanel feed={feed}/></main>
}

function LocationsPage({location,setLocation,feed}:{location:string;setLocation:(v:string)=>void;feed:Feed}){
 const [saved,setSaved]=useState<SavedLocation[]>([]),[open,setOpen]=useState(false),[query,setQuery]=useState(""),[results,setResults]=useState<LocationSearchResult[]>([]),[status,setStatus]=useState("");
 useEffect(()=>{getLocations().then(setSaved).catch(()=>setStatus("Saved locations could not be loaded."))},[]);
 useEffect(()=>{if(query.trim().length<2){setResults([]);return}const timer=window.setTimeout(()=>searchLocations(query).then(setResults).catch(()=>setStatus("Search is temporarily unavailable.")),300);return()=>window.clearTimeout(timer)},[query]);
 const save=async(name:string)=>{setStatus("Saving…");try{const item=await addLocation(name);setSaved(current=>current.some(x=>x.id===item.id)?current:[...current,item]);setLocation(name);setOpen(false);setQuery("");setStatus(`${name} saved and activated.`)}catch(error){setStatus(error instanceof Error?error.message:"Could not save location.")}};
 return <main className="page"><PageHeading eyebrow="Saved weather contexts" title="Your locations" copy="Search, save, and switch places. Every selection refreshes live weather and recommendations." action={<button className="primary-cta" onClick={()=>setOpen(!open)}><Plus/> {open?"Close":"Add location"}</button>}/>
 {open&&<section className="add-location-panel"><label className="location-search"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search city or district"/></label><div className="location-results">{results.map(result=><button key={`${result.latitude}-${result.longitude}`} onClick={()=>save(result.name)}><MapPin/><span><b>{result.name}</b><small>{[result.admin1,result.country].filter(Boolean).join(", ")}</small></span><Plus/></button>)}</div></section>}
 {status&&<p className="form-message" role="status">{status}</p>}<div className="location-grid">{saved.map(item=><button key={item.id} className={location===item.name?"active":""} onClick={()=>setLocation(item.name)}><div><span><MapPin/></span><em>{item.label}</em></div><h2>{item.name}</h2><p>{location===item.name?feed.weather.condition:"Select to load live weather"}</p><strong>{location===item.name?`${feed.weather.temperature}°C`:"Live"}</strong>{location===item.name&&<small><Check/> Active location</small>}</button>)}</div><section className="locations-note"><LocateFixed/><div><h3>Weather follows your context</h3><p>Changing location now fetches a live forecast and re-runs the same active persona through the recommendation engine.</p></div></section></main>
}

function ProfilePage({persona,setPersona,onSaved}:{persona:Persona;setPersona:(p:Persona)=>void;onSaved:()=>void}){
 const [profile,setProfile]=useState<UserProfile|null>(null),[activities,setActivities]=useState<string[]>([]),[custom,setCustom]=useState(""),[notifications,setNotifications]=useState(true),[protection,setProtection]=useState<string[]>([]),[commute,setCommute]=useState(""),[routine,setRoutine]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;getProfile().then(value=>{if(!active)return;setProfile(value);setActivities(value.activities);setNotifications(value.notifications_enabled);setProtection(value.extra_protection);setCommute(value.commute_time??"");setRoutine(value.routine??"")}).catch(()=>setStatus("Profile could not be loaded. Reload before editing."));return()=>{active=false}},[]);
 const toggleActivity=(activity:string)=>setActivities(current=>current.includes(activity)?current.filter(x=>x!==activity):[...current,activity]);
 const addPreference=()=>{const value=custom.trim();if(!value)return;setActivities(current=>current.includes(value)?current:[...current,value]);setCustom("")};
 const save=async()=>{if(!profile||busy)return;setBusy(true);setStatus("Saving preferences…");try{const pending=custom.trim();const next=pending&&!activities.includes(pending)?[...activities,pending]:activities;const updated=await updatePreferences({persona,activities:next,notifications_enabled:notifications,extra_protection:protection,commute_time:commute||null,routine});setProfile(updated);setActivities(next);setCustom("");onSaved();setStatus("Preferences saved. Your briefing is being updated.")}catch{setStatus("Could not save preferences. Please try again.")}finally{setBusy(false)}};
 return <main className="page"><PageHeading eyebrow="Personalization preferences" title="Your profile" copy="Your activities, protection needs and daily routine shape the briefing." action={<button className="primary-cta" disabled={busy||!profile} onClick={save}><Save/>{busy?"Saving…":"Save preferences"}</button>}/><section className="profile-grid"><div className="panel-card profile-card"><span className="avatar large">{profile?.name.charAt(0)??"A"}</span><div><h2>{profile?.name??"Loading profile…"}</h2><p>{profile?.location} · Saved profile</p></div></div><div className="panel-card settings-card"><span className="eyebrow">Active persona</span><div className="profile-personas">{personas.map(p=>{const meta=personaMeta[p],Icon=meta.icon;return <button key={p} className={persona===p?"active":""} onClick={()=>setPersona(p)}><Icon/><span><b>{meta.title}</b><small>{meta.focus}</small></span>{persona===p&&<Check/>}</button>})}</div></div><div className="panel-card preference-card"><span className="eyebrow">Activities and interests</span><h2>What matters to you</h2><div>{Array.from(new Set(["Cycling","Walking","School commute","Outdoor events","Gardening","Travel","Outdoor work",...activities])).map(x=><button className={activities.includes(x)?"active":""} onClick={()=>toggleActivity(x)} key={x} aria-pressed={activities.includes(x)}>{x}</button>)}</div><div className="add-preference"><input maxLength={60} value={custom} onChange={e=>setCustom(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addPreference()} placeholder="Add another preference"/><button onClick={addPreference} disabled={!custom.trim()}><Plus/>Add preference</button></div><p>Recognized activities adjust relevant risk factors; custom interests are included in your explanation.</p></div><div className="panel-card preference-list"><h2>Routine and protection</h2><label className="onboard-label">Typical departure time<input type="time" value={commute} onChange={e=>setCommute(e.target.value)}/></label><label className="onboard-label">Daily needs<input maxLength={200} value={routine} onChange={e=>setRoutine(e.target.value)} placeholder="e.g. school pickup, evening walk"/></label><h3>Extra protection</h3><div className="protection-grid">{["Children","Elderly family members","Weather-sensitive needs","Outdoor workers"].map(item=><label key={item}><input type="checkbox" checked={protection.includes(item)} onChange={()=>setProtection(current=>current.includes(item)?current.filter(x=>x!==item):[...current,item])}/>{item}</label>)}</div><button className="preference-row" aria-pressed={notifications} onClick={()=>setNotifications(value=>!value)}><span>Priority notifications</span><b>{notifications?"Enabled":"Paused"}<ChevronRight/></b></button><p>Use Save preferences to apply these settings.</p></div></section>{status&&<p className="form-message profile-message" role="status">{status}</p>}</main>
}

function DemoPage({persona,setPersona}:{feed:Feed;persona:Persona;setPersona:(p:Persona)=>void}){
 const [demo,setDemo]=useState<Feed|null>(null),[error,setError]=useState("");
 useEffect(()=>{let active=true;setDemo(null);getDemo(persona).then(value=>{if(active){setDemo(value);setError("")}}).catch(()=>{if(active)setError("Demo unavailable")});return()=>{active=false}},[persona]);
 return <main className="page demo-page"><PageHeading eyebrow="Explicit sample scenario" title="Personalization lab" copy="Compare personas using the same sample weather. This is not live weather."/><PersonaPicker persona={persona} setPersona={setPersona}/>{error&&<p role="alert">{error}</p>}{demo&&<><WeatherHero feed={demo}/><ImpactCard feed={demo}/>{demo.recommendations.map(item=><section className="panel-card" key={item.id}><h2>{item.title}</h2><p>{item.message}</p><b>{item.action}</b><details><summary>Why am I seeing this?</summary>{item.reason.map(reason=><p key={reason}>{reason}</p>)}</details></section>)}</>}</main>
}

function Onboarding({persona,setPersona,location,setLocation,complete}:{persona:Persona;setPersona:(p:Persona)=>void;location:string;setLocation:(v:string)=>void;complete:()=>void}){
 const [step,setStep]=useState(1),[activities,setActivities]=useState<string[]>(["Cycling"]),[protection,setProtection]=useState<string[]>([]),[departure,setDeparture]=useState("08:30"),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState("");
 const toggle=(value:string,list:string[],setter:(v:string[])=>void)=>setter(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
 const finish=async()=>{if(saving)return;setSaving(true);setSaveError("");try{await updatePreferences({persona,location,activities,extra_protection:protection,commute_time:departure});complete()}catch{setSaveError("Could not save your profile. Please retry.")}finally{setSaving(false)}};
 return <main className="onboarding"><header><Logo/><span>Step {step} of 3</span></header><div className="progress"><i style={{width:`${step/3*100}%`}}/></div><section>
   {step===1&&<div className="onboard-panel"><span className="eyebrow">Your weather context</span><h1>Where should Mausam+ watch?</h1><p>Choose the location used for your first personalized briefing.</p><button className="location-use" onClick={()=>setLocation("Ahmedabad")}><LocateFixed/><span><b>Use Ahmedabad</b><small>Choose Ahmedabad as your starting city</small></span><Check/></button><label className="onboard-label">Or choose a starting city<select value={location} onChange={e=>setLocation(e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}</select></label></div>}
   {step===2&&<div className="onboard-panel wide"><span className="eyebrow">Personalize priorities</span><h1>Who are you planning for?</h1><p>Select the context that should change card order, thresholds and alert language.</p><div className="onboard-personas">{onboardingPersonas.map(p=>{const m=personaMeta[p],Icon=m.icon;return <button key={p} className={persona===p?"active":""} onClick={()=>setPersona(p)}><Icon/><span><b>{m.title}</b><small>{personaDetails[p].subtitle}</small></span>{persona===p&&<Check/>}</button>})}</div></div>}
   {step===3&&<div className="onboard-panel wide"><span className="eyebrow">Preventive preferences</span><h1>What deserves extra protection?</h1><p>This adjusts alert priority. You can change it later.</p><h3>Activities and routines</h3><div className="choice-chips">{["Cycling","Walking","School commute","Farming","Outdoor work","Travel","Outdoor events"].map(x=><button key={x} className={activities.includes(x)?"active":""} onClick={()=>toggle(x,activities,setActivities)}>{x}</button>)}</div><h3>Extra protection for</h3><div className="protection-grid">{["Children","Elderly family members","Outdoor workers","Farmers","Weather-sensitive needs","Travelers","Students"].map(x=><label key={x}><input type="checkbox" checked={protection.includes(x)} onChange={()=>toggle(x,protection,setProtection)}/><span>{x}</span></label>)}</div>{(persona==="commuter"||activities.includes("School commute"))&&<label className="onboard-label">Typical departure time<input type="time" value={departure} onChange={e=>setDeparture(e.target.value)}/></label>}</div>}
   {saveError&&<p role="alert">{saveError}</p>}<footer><button className="back" disabled={step===1} onClick={()=>setStep(step-1)}>Back</button><button className="continue" disabled={saving} onClick={()=>step<3?setStep(step+1):finish()}>{saving?"Saving…":step<3?"Continue":"Show my weather intelligence"}<ArrowRight/></button></footer>
 </section></main>
}

function Loading(){return <div className="loading-page"><div className="skeleton sk-nav"/><div><div className="skeleton sk-head"/><div className="skeleton sk-hero"/><div className="skeleton sk-card"/></div></div>}

function Landing({enter}:{enter:()=>void}){return <main className="landing"><header><Logo/><nav><a href="#difference">How it works</a><button onClick={enter}>Open Mausam+ <ArrowRight/></button></nav></header><section className="landing-hero"><div><span className="eyebrow"><Sparkles/> Personalized weather intelligence</span><h1>Weather that understands <em>your day.</em></h1><p>Mausam+ turns a forecast into a clear decision shaped by your activity, place and priorities.</p><div className="landing-actions"><button onClick={enter}>Build my weather profile <ArrowRight/></button><a href="#difference">See the difference</a></div><small><ShieldCheck/> Transparent rules · Clearly labelled demo data</small></div><div className="landing-visual"><span className="visual-label">Ahmedabad · Same weather</span><CloudSun/><strong>34°C</strong><p>Hazy sunshine · Rain later</p><div className="floating-insight first">🚴 <span><b>Cyclist</b>Ride before 8 AM</span></div><div className="floating-insight second">🧳 <span><b>Traveler</b>Pack rain protection</span></div></div></section><section className="difference" id="difference"><span className="eyebrow">The Mausam+ difference</span><h2>One forecast. Four useful decisions.</h2><div>{corePersonas.map(p=>{const meta=personaMeta[p],Icon=meta.icon;return <article key={p}><Icon/><span>{meta.label}</span><b>{p==="fitness"?"Best activity time":p==="family"?"Safer outdoor plans":p==="agriculture"?"Rain-aware planning":"Destination guidance"}</b><ChevronRight/></article>})}</div><button onClick={enter}>Experience personalization <ArrowRight/></button></section></main>}

export default function App(){
 const [stage,setStage]=useState<"landing"|"onboarding"|"app">(()=>sessionStorage.getItem("mausam-mvp-ready")==="yes"?"app":"landing"),[view,setView]=useState<View>("home"),[persona,setPersona]=useState<Persona>("fitness"),[location,setLocation]=useState("Ahmedabad"),[feed,setFeed]=useState<Feed|null>(null),[error,setError]=useState(""),[ready,setReady]=useState(false),[reload,setReload]=useState(0);
 const request=useRef<AbortController|null>(null);
 const writes=useRef<Promise<unknown>>(Promise.resolve());
 useEffect(()=>{let active=true;getProfile().then(profile=>{if(active){setPersona(profile.persona);setLocation(profile.location);setReady(true)}}).catch(()=>{if(active){setError("Profile could not be loaded. Check the connection and retry.");setReady(true)}});return()=>{active=false}},[]);
 const refresh=useCallback(async()=>{request.current?.abort();const controller=new AbortController();request.current=controller;try{const value=await getFeed(persona,location,controller.signal);if(!controller.signal.aborted){setFeed(value);setError("")}}catch{if(!controller.signal.aborted)setError("Weather could not be refreshed. Any displayed forecast may be out of date.")}},[persona,location]);
 const persist=useCallback((changes:Partial<UserProfile>)=>{writes.current=writes.current.catch(()=>undefined).then(()=>updatePreferences(changes)).catch(()=>setError("Your context could not be saved. Please retry in Profile."))},[]);
 const changePersona=useCallback((value:Persona)=>{setPersona(value);persist({persona:value})},[persist]);
 const changeLocation=useCallback((value:string)=>{setLocation(value);persist({location:value})},[persist]);
 useEffect(()=>{if(stage!=="app"||!ready)return;setFeed(null);refresh();const timer=window.setInterval(refresh,300000);const onFocus=()=>refresh();window.addEventListener("focus",onFocus);return()=>{request.current?.abort();window.clearInterval(timer);window.removeEventListener("focus",onFocus)}},[stage,ready,refresh,reload]);
 if(stage==="landing")return <Landing enter={()=>setStage("onboarding")}/>;
 if(stage==="onboarding")return <Onboarding persona={persona} setPersona={setPersona} location={location} setLocation={setLocation} complete={()=>{sessionStorage.setItem("mausam-mvp-ready","yes");setStage("app")}}/>;
 if(error&&!feed)return <div className="error-page"><AlertTriangle/><h1>Weather data is unavailable</h1><p>{error}</p><button onClick={()=>{setError("");setReload(value=>value+1)}}>Try again</button></div>;
 if(!feed)return <Loading/>;
 let content:React.ReactNode;
 switch(view){case"forecast":content=<ForecastPage feed={feed} persona={persona}/>;break;case"alerts":content=<AlertsPage feed={feed} persona={persona}/>;break;case"locations":content=<LocationsPage location={location} setLocation={changeLocation} feed={feed}/>;break;case"profile":content=<ProfilePage persona={persona} setPersona={changePersona} onSaved={refresh}/>;break;case"demo":content=<DemoPage feed={feed} persona={persona} setPersona={changePersona}/>;break;default:content=<HomePage feed={feed} persona={persona} setPersona={changePersona} setView={setView}/>}
 return <AppShell view={view} setView={setView} feed={feed} location={location} setLocation={changeLocation} onRefresh={refresh}>{error&&<p className="form-message" role="alert">{error}<button onClick={refresh}>Retry update</button></p>}{content}</AppShell>;
}
